### PR TITLE
Fix remaining MacOS build issues

### PR DESCRIPTION
**Pull request by duxet**
With these changes project will compile successfully on MacOS by adding `-DOPENSSL_ROOT_DIR=$(brew --prefix openssl)` parameter to cmake.

I had to add `set(Protobuf_USE_STATIC_LIBS ON)` to fix issue with:
```
$ bin/autoapp
[libprotobuf ERROR google/protobuf/descriptor_database.cc:58] File already exists in database: AVMediaAckIndicationMessage.proto
[libprotobuf FATAL google/protobuf/descriptor.cc:1394] CHECK failed: generated_database_->Add(encoded_file_descriptor, size):
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: generated_database_->Add(encoded_file_descriptor, size):
```

### CODE REVIEW

**Comment by f1xpl** [comment]
Hi,
thanks for your effort. I will test those changes on the Raspberry PI, Ubuntu and Windows and merge the pull request.

**Comment by f1xpl** [comment]
Hello,
I tested compilation on Ubuntu 17.10. There is a problem with linking protobuf to libaasdk.so. Looks like protobuf for ubuntu is compiled without -fPIC.

```
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(arena.o): relocation R_X86_64_TPOFF32 against symbol `_ZN6google8protobuf5Arena13thread_cache_E' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(descriptor.o): relocation R_X86_64_PC32 against symbol `_ZTIN6google8protobuf15DescriptorProtoE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
```

```
$ ld --version
GNU ld (GNU Binutils for Ubuntu) 2.29.1
Copyright (C) 2017 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

```
$ protoc --version
libprotoc 3.0.0
```

```
$ gcc --version
gcc (Ubuntu 7.2.0-8ubuntu3.2) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
$ uname -a
Linux VirtualBox 4.13.0-36-generic #40-Ubuntu SMP Fri Feb 16 20:07:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by duxet** [comment]
I have removed the change with static protobuf library, at least it will build successfully on Mac OS. I will try to find a better way to fix the issue with duplicated proto files.

**Comment by f1xpl** [comment]
Great, thank you. I will check it as soon as possible.

**Comment by f1xpl** [comment]
Hello @duxet,
I went in same troubles (duplicated defitions of protobuf messages, not visible open ssl) as you building OpenAuto using MinGW-w64. I commited some changes based on your pull request. Could you please test compilation process on MacOS once more? Also please test issue with duplicated protobuf messages.

**Comment by duxet** [comment]
```
aasdk/src/Transport/SSLWrapper.cpp:55:43: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    auto bio = BIO_new_mem_buf(certificate.c_str(), certificate.size());
```

**Comment by f1xpl** [comment]
@duxet I think it is related to #include <string> in SSLWrapper.cpp. I did not include this change. Could you please rebase your pull request?

**Comment by duxet** [comment]
Done :)

**Comment by f1xpl** [comment]
@duxet And now it is compilling :)? If yes, I will merge this pull request immediately.

**Comment by duxet** [comment]
Yeah, it's working fine now.

**Pull request merged**
